spring:
  application:
    name: learn
  datasource:
    url: "jdbc:mysql://localhost:3306/learn_spring"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    auditor-aware-ref: auditorAwareImpl

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationInMs: 86400000
  jwtRefreshExpirationInMs: 604800000

cloud:
  name: ${CLOUD_NAME}
  key: ${CLOUD_KEY}
  secret: ${CLOUD_SECRET}
#    url: ${DBMS_CONNECTION:jdbc:mysql://mysql-container:3306/blogdb}
